name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up .NET Core
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0' # Asegúrate de que usa .NET 6

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build the application
    - name: Build the application
      run: dotnet build --configuration Release --no-restore

    # Publish the application
    - name: Publish the application
      run: dotnet publish --configuration Release --output D:\a\MyMvcApp-Contact-Databse-Application\MyMvcApp-Contact-Databse-Application\bin\Release\net6.0\MyMvcApp

    # Upload artifact for deployment
    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v3
      with:
        name: mymvcapp-artifact
        path: D:\a\MyMvcApp-Contact-Databse-Application\MyMvcApp-Contact-Databse-Application\bin\Release\net6.0\MyMvcApp

    # Deploy to Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'myMvcApp3' # Reemplaza con el nombre de tu App Service
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: D:\a\MyMvcApp-Contact-Databse-Application\MyMvcApp-Contact-Databse-Application\bin\Release\net6.0\MyMvcApp